language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
  - 1.27.0
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
  - osx

before_script:
  - env

script:
  - cargo build --all
  - cargo test --all

notifications:
  email:
    on_success: never
    on_failure: never
