[package]
name = "jsonrpc-client-pubsub"
version = "0.1.0"
authors = ["Emīls Piņķis <emils@mullvad.net>"]

[dependencies]
jsonrpc-client-core = { version = "0.5", path = "../core" }
futures = "~0.1.24"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
tokio = "0.1"
log = "*"
